const PDFDocument = require('pdfkit')

const PURPLE = '#5B4FE9'
const DARK = '#0F172A'
const MID = '#475569'
const LIGHT = '#94A3B8'
const RULE = '#E2E8F0'
const BG_BAR = '#F1F5F9'

function scoreBar(doc, label, score, x, y) {
  const barWidth = 220
  const value = Number(score)
  const normalized = Number.isFinite(value) ? Math.max(0, Math.min(10, value)) : 0

  doc.fontSize(10).fillColor(MID).text(label, x, y)
  doc.roundedRect(x, y + 16, barWidth, 8, 4).fill(BG_BAR)
  if (normalized > 0) {
    doc.roundedRect(x, y + 16, barWidth * normalized / 10, 8, 4).fill(PURPLE)
  }
  doc.fontSize(10).fillColor(DARK).text(`${normalized}/10`, x + barWidth + 8, y + 14)
}

function parseList(value) {
  if (Array.isArray(value)) return value
  if (!value) return []
  try {
    const parsed = JSON.parse(value)
    return Array.isArray(parsed) ? parsed : []
  } catch {
    return []
  }
}

async function generateReportPdf({ candidate, interview, report }) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 48, bufferPages: true })
    const chunks = []
    doc.on('data', chunk => chunks.push(chunk))
    doc.on('end', () => resolve(Buffer.concat(chunks)))
    doc.on('error', reject)

    const left = 48
    const pageWidth = doc.page.width - 96

    doc.rect(0, 0, doc.page.width, 64).fill(PURPLE)
    doc.fontSize(22).fillColor('#FFFFFF').font('Helvetica-Bold').text('Screeno', left, 20)
    doc.fontSize(11).font('Helvetica').fillColor('#DDD9FF').text('Interview Report', left + 100, 24)

    const name = `${candidate.first_name || ''} ${candidate.last_name || ''}`.trim()
    doc.moveDown(2)
    doc.fontSize(18).fillColor(DARK).font('Helvetica-Bold').text(name || 'Candidate', left)
    doc.fontSize(10).fillColor(MID).font('Helvetica')
      .text(candidate.email || '', left)
      .text(
        `Difficulty: ${interview.difficulty || 'medium'} | ${new Date(interview.created || Date.now()).toDateString()}`,
        left
      )

    doc.moveDown(0.5)
    doc.moveTo(left, doc.y).lineTo(left + pageWidth, doc.y).strokeColor(RULE).stroke()
    doc.moveDown(0.8)

    const scoreY = doc.y
    const overall = Number.isFinite(Number(report.overall_score)) ? Number(report.overall_score) : 0
    doc.fontSize(48).fillColor(PURPLE).font('Helvetica-Bold')
      .text(String(overall), left, scoreY, { width: 80, align: 'center' })
    doc.fontSize(10).fillColor(LIGHT).font('Helvetica')
      .text('Overall', left, scoreY + 52, { width: 80, align: 'center' })

    const barsX = left + 100
    const barsY = scoreY + 4
    scoreBar(doc, 'Confidence', report.confidence, barsX, barsY)
    scoreBar(doc, 'Tech Knowledge', report.tech_knowledge, barsX, barsY + 44)
    scoreBar(doc, 'Communication', report.communication, barsX + 300, barsY)
    scoreBar(doc, 'Problem Solving', report.problem_solving, barsX + 300, barsY + 44)

    doc.y = barsY + 88
    doc.moveDown(0.5)
    doc.moveTo(left, doc.y).lineTo(left + pageWidth, doc.y).strokeColor(RULE).stroke()
    doc.moveDown(0.8)

    doc.fontSize(13).fillColor(DARK).font('Helvetica-Bold').text('Summary', left)
    doc.moveDown(0.3)
    doc.fontSize(10).fillColor(MID).font('Helvetica')
      .text(report.summary || 'No summary available.', left, doc.y, {
        width: pageWidth,
        lineGap: 4,
      })
    doc.moveDown(1)

    const strengths = parseList(report.strengths)
    if (strengths.length > 0) {
      doc.fontSize(13).fillColor(DARK).font('Helvetica-Bold').text('Strengths', left)
      doc.moveDown(0.3)
      for (const strength of strengths) {
        doc.fontSize(10).fillColor(MID).font('Helvetica')
          .text(`- ${strength}`, left + 8, doc.y, { width: pageWidth - 8, lineGap: 3 })
      }
      doc.moveDown(1)
    }

    if (interview.context_text) {
      doc.moveTo(left, doc.y).lineTo(left + pageWidth, doc.y).strokeColor(RULE).stroke()
      doc.moveDown(0.6)
      doc.fontSize(11).fillColor(DARK).font('Helvetica-Bold').text('Assessment Context', left)
      doc.moveDown(0.3)
      const excerpt = interview.context_text.slice(0, 600)
      doc.fontSize(9).fillColor(LIGHT).font('Helvetica')
        .text(excerpt + (interview.context_text.length > 600 ? '...' : ''), left, doc.y, {
          width: pageWidth,
          lineGap: 3,
        })
    }

    const pages = doc.bufferedPageRange()
    for (let index = 0; index < pages.count; index += 1) {
      doc.switchToPage(pages.start + index)
      doc.fontSize(8).fillColor(LIGHT)
        .text(`Generated by Screeno | ${new Date().toDateString()}`, left, doc.page.height - 36, {
          width: pageWidth,
          align: 'center',
        })
    }

    doc.end()
  })
}

module.exports = { generateReportPdf }
